version: "3.8"

services:
  postgres:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_DB: "bankline_db"
      POSTGRES_PASSWORD: "bl123"
    ports:
      - 5432:5432
    volumes:
      - c:/bankline/docker/share/pg/13/data:/var/lib/postgresql/data
    networks:
      - bankline

  pgadmin:
    image: dpage/pgadmin4:5.6
    environment:
      PGADMIN_DEFAULT_EMAIL: "contato@bankline.com.br"
      PGADMIN_DEFAULT_PASSWORD: "bl123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - bankline

networks:
  bankline:
    driver: bridge