server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankline_db
    username: postgres
    password: bl123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update